# Generated by Django 4.2.7 on 2023-11-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Documento',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
