# Generated by Django 4.2.7 on 2023-11-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_remove_user_documento_alter_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
