# Generated by Django 4.2.6 on 2023-11-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('documento', models.IntegerField()),
                ('ficha', models.IntegerField()),
                ('photo', models.ImageField(upload_to='fotos_usuarios')),
            ],
        ),
    ]
