# Generated by Django 4.2.7 on 2023-11-28 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refe_personales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_person', models.CharField(max_length=50)),
                ('Apellido_person', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('N_celular', models.IntegerField()),
                ('Inforamcion_adi', models.TextField()),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Refe_empresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Empresa', models.CharField(max_length=50)),
                ('Nombre_Jefe', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('N_celular', models.IntegerField()),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Informacion_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('Apellido', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=50)),
                ('Celular', models.IntegerField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Fecha', models.DateField()),
                ('Tipod', models.CharField(choices=[('C.C', 'C.C'), ('C.E', 'C.E'), ('PAS', 'PAS'), ('TI', 'TI')], max_length=50)),
                ('N_documento', models.IntegerField()),
                ('Genero', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=50)),
                ('Edad', models.IntegerField()),
                ('Civil', models.CharField(choices=[('Casado', 'Casado'), ('Union libre', 'Union libre'), ('Soltero', 'Soltero')], max_length=50)),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_empresa', models.CharField(max_length=50)),
                ('Cargo', models.CharField(max_length=50)),
                ('Fecha_Inicio', models.DateField()),
                ('Fecha_Finalizacion', models.DateField()),
                ('Funciones', models.TextField()),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Educacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Archivo', models.FileField(upload_to='Archivo_Educacion')),
                ('Nombre_Instituto', models.CharField(max_length=50)),
                ('Ano_graduacion', models.DateField()),
                ('Tiempo', models.IntegerField()),
                ('Usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
