# Generated by Django 4.2.7 on 2023-11-29 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_emp', models.CharField(max_length=50)),
                ('NIT', models.CharField(max_length=15)),
                ('Email', models.CharField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
            ],
        ),
    ]
